unit tests for using the LocationHeaderMixin subclasses successfully. Fixes: TypeError: 'MovedPermanently' object does not support item assignment Fixes: AttributeError: 'MovedPermanently' object has no attribute 'allowed_schemes'